# /etc/dhcp/dhcpd.conf file
#
# ISC DHCP server configuration for two subnets used in PXE network booting.
# Defines IP pools, gateway, lease times, and PXE boot settings for each network:
#   - Main network    (192.168.1.0/24): pool 192.168.1.50-100, gateway 192.168.1.1
#   - Internal network (10.0.0.0/24):  pool 10.0.0.50-100,    gateway 10.0.0.1
# Both subnets point to their respective server for PXE boot (next-server)
# and load the EFI bootloader (syslinux.efi). DNS provided by Cloudflare (1.1.1.1).

# 192.168.1.0/24 subnet configuration
subnet 192.168.1.0 netmask 255.255.255.0 {
    range 192.168.1.50 192.168.1.100;
    option routers 192.168.1.1;
    default-lease-time 3600;
    max-lease-time 86400;
    next-server 192.168.1.1;
    option bootfile-name "pxelinux.0";
}

# 10.0.0.0/24 subnet configuration
subnet 10.0.0.0 netmask 255.255.255.0 {
    range 10.0.0.50 10.0.0.100;
    option routers 10.0.0.1;
    default-lease-time 3600;
    max-lease-time 86400;
    next-server 10.0.0.1;
    option bootfile-name "pxelinux.0";
}

# --- Static addresses for MAIN network ---

# --- Load balancer lvs
host lvs-01 {
    hardware ethernet 08:00:27:00:01:0A; # Change with real MAC
    fixed-address 192.168.1.10;
    filename "pxelinux.0";
}

host router-main {
    hardware ethernet 08:00:27:00:00:01;
    fixed-address 192.168.1.2;
    filename "pxelinux.0";
}

host router-internal {
    hardware ethernet 08:00:27:00:00:02;
    fixed-address 10.0.0.2;
    filename "pxelinux.0";
}

# --- http servers
host http-01 {
    hardware ethernet 08:00:27:00:01:0B;
    fixed-address 192.168.1.11;
    filename "pxelinux.0";
}

host http-02 {
    hardware ethernet 08:00:27:00:01:0C;
    fixed-address 192.168.1.12;
    filename "pxelinux.0";
}

# --- Static addresses for INTERNAL network ---

# --- Masters
host master-01 {
    hardware ethernet 08:00:27:00:02:0A;
    fixed-address 10.0.0.10;
    filename "pxelinux.0";
}

host master-02 {
    hardware ethernet 08:00:27:00:02:0B;
    fixed-address 10.0.0.11;
    filename "pxelinux.0";
}

# --- Workers
host worker-01 {
    hardware ethernet 08:00:27:00:02:0C;
    fixed-address 10.0.0.12;
    filename "pxelinux.0";
}

host worker-02 {
    hardware ethernet 08:00:27:00:02:0D;
    fixed-address 10.0.0.13;
    filename "pxelinux.0";
}

# --- Monitor
host monitor-01 {
    hardware ethernet 08:00:27:00:02:0E;
    fixed-address 10.0.0.14;
    filename "pxelinux.0";
}

# --- Static addresses for EXT network ---
subnet 10.0.2.0 netmask 255.255.255.0 {
    range 10.0.2.50 10.0.2.100;
    option routers 10.0.2.1;
    default-lease-time 3600;
    max-lease-time 86400;
    next-server 10.0.2.1;
    option bootfile-name "pxelinux.0";
}

host lvs-ext {
    hardware ethernet 08:00:27:00:01:0F;
    fixed-address 10.0.2.10;
    filename "pxelinux.0";
}

# DNS definitions for all the networks
option domain-name-servers 1.1.1.1, 1.0.0.1;

authoritative;
