---
- import_playbook: 00-bootstrap-jumpstart.yml
- import_playbook: 04-glusterfs.yml
- import_playbook: 05-swarm.yml
- import_playbook: 06-web.yml
- import_playbook: 14-reboot-zabbix.yml
- import_playbook: 11-routing.yml
- import_playbook: 13-routing-final.yml